version: '3'
services:
    gohelloworld:
        build: .
        image: gohelloworld:latest
        ports: 
            - "8080:8080"
    gobase:
        image: golang:latest
        working_dir: "/app/src"
        volumes: 
            - "./:/app"
    awscli:
        image: amazon/aws-cli
        working_dir: "/app"
        env_file: 
            - ./aws.env

    wdio-testlocal:
        image: localtest-hello-world
        working_dir: "/app"
        volumes:
            - "./test:/app"
        environment:
            - BROWSER=$BROWSER